name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: templates

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.png