name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: wget xz-utils make imagemagick

    - name: Install typst
      run: |
        wget https://github.com/typst/typst/releases/download/v0.4.0/typst-x86_64-unknown-linux-musl.tar.xz
        tar xvf typst-x86_64-unknown-linux-musl.tar.xz
        echo typst-x86_64-unknown-linux-musl >> $GITHUB_PATH

    - name: Build
      run: |
        sudo rm /etc/ImageMagick-6/policy.xml #disable pesky security check
        make