name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: make imagemagick

    - name: Install typst
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: typst/typst
        tag: v0.4.0

    - name: Build
      run: make