name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: wget xz-utils make imagemagick ghostscript unzip fontconfig

    - name: Install typst
      run: |
        wget https://github.com/typst/typst/releases/download/v0.4.0/typst-x86_64-unknown-linux-musl.tar.xz
        tar xvf typst-x86_64-unknown-linux-musl.tar.xz
        echo typst-x86_64-unknown-linux-musl >> $GITHUB_PATH

    - name: Install fonts
      run: |
        wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/ProFont.zip
        unzip -d ~/.fonts ProFont.zip

    - name: Build
      run: |
        sudo rm /etc/ImageMagick-6/policy.xml #disable pesky security check
        make

    - name: Upload built templates to artifact store
      uses: actions/upload-artifact@v3
      with:
        name: templates
        path: "*.png"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.png
          README.md
          LICENSE